security:
    encoders:
        App\Entity\User: bcrypt

    providers:
        users_in_memory: { memory: null }
        custom_user_provider:
            id: 'app_user_provider'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            http_basic: ~
            provider: custom_user_provider
            anonymous: ~
            pattern: ^/
            form_login:
                login_path: login
                check_path: login_check
                always_use_default_target_path: true
                default_target_path: /
                provider: custom_user_provider
            logout: ~
            logout_on_user_change: true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/users, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
